listen: :443

auth:
  type: password
  password: test123

masquerade:
  type: proxy
  proxy:
    url: https://www.google.com

acme:
  domains:
    - hysteria-on-railway.onrender.com
  email: majdiisfahani@gmail.com

